#!/bin/bash
case $1 in
    -d)
      read -p "podaj nazwę pliku" plik
      sort -n -k1,1 $plik | head -n5
      ;;
    -v)
      read -p "podaj nazwę pliku" plik
      grep -v 'linux' $plik
      ;;
    -x)
      read -p "podaj nazwę pliku " plik
      tac $plik
      ;;
    -y)
      ls -lt | head -n 10
      ;;
    -z)
      read -p "podaj nazwę pliku " plik
      tr '[:lower:]' '[:upper:]' < $plik
      ;;
esac
echo "1 Wyświetl linie z 5 słowami"
echo "2 Wyświetl zawartość w odwrotnej kolejności liter"
echo "3 Wyświetl pliki z co najmniej 3 samogłoskami"
echo "4 Zlicz słowa w pliku"
echo "5 Suma rozmiarów plików w katalogu"
read -p "Wybierz opcję : " opcja
case $opcja in
        "1")
            read -p "podaj nazwę pliu: " nazwa
            grep -E '([^[:space:]]+[[:space:]]+){4}[^[:space:]]+' $nazwa
          ;;
        "2")
            read -p "podaj nazwę pliku: " nazwa
            tac $nazwa
          ;;
         "3")
            find . -maxdepth 1 -type f -iname '*[aeiouAEIOU]*[aeiouAEIOU]*[aeiouAEIOU]*'
          ;;
        "4")
            read -p "Podaj nazwę pliku: " plik
            echo "Liczba słów w pliku:"
            wc -w < "$plik"
          ;;
        "5")
            echo "Suma rozmiarów wszystkich plików w katalogu:"
            du -ch | tail -n 1
          ;;

esac
